//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updator.Downloader.CLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Updator.Downloader.CLI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [blue]Updating launcher[/].
        /// </summary>
        internal static string CheckDownloaderUpdate {
            get {
                return ResourceManager.GetString("CheckDownloaderUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]Update launcher failed, please visit software website to manually update.[/].
        /// </summary>
        internal static string DonwloaderUpdateFailed {
            get {
                return ResourceManager.GetString("DonwloaderUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [yellow]Downloading description[/].
        /// </summary>
        internal static string DownloadDescription {
            get {
                return ResourceManager.GetString("DownloadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [palegreen1]Downloaded description[/].
        /// </summary>
        internal static string DownloadedDescription {
            get {
                return ResourceManager.GetString("DownloadedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [palegreen1]Downloaded update files[/].
        /// </summary>
        internal static string DownloadedUpdateFiles {
            get {
                return ResourceManager.GetString("DownloadedUpdateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [yellow]Downloading update files[/].
        /// </summary>
        internal static string DownloadUpdateFiles {
            get {
                return ResourceManager.GetString("DownloadUpdateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [green]Press ENTER to continue[/].
        /// </summary>
        internal static string EnterToContinue {
            get {
                return ResourceManager.GetString("EnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [yellow]Restart application if it seems stucked for too long[/].
        /// </summary>
        internal static string KillWhenTooLong {
            get {
                return ResourceManager.GetString("KillWhenTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]No[/].
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [palegreen1]Self update succeed.[/].
        /// </summary>
        internal static string SelfUpdateDone {
            get {
                return ResourceManager.GetString("SelfUpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should only be one enabled source in [underline red]sources.json[/]. Please check again!.
        /// </summary>
        internal static string ShouldUniqueSource {
            get {
                return ResourceManager.GetString("ShouldUniqueSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File [underline red]sources.json[/] not found. Please reinstall application..
        /// </summary>
        internal static string SourcesNotFound {
            get {
                return ResourceManager.GetString("SourcesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [blue]Update complete, launching {0} [/].
        /// </summary>
        internal static string UpdateDone {
            get {
                return ResourceManager.GetString("UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [yellow]Found new version of launcher ({0} -&gt; {1}), update now?[/].
        /// </summary>
        internal static string UpdateDownloader {
            get {
                return ResourceManager.GetString("UpdateDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [palegreen1]Updated sources.json[/].
        /// </summary>
        internal static string UpdatedSourcesJson {
            get {
                return ResourceManager.GetString("UpdatedSourcesJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [blue]Update Logs[/].
        /// </summary>
        internal static string UpdateLogs {
            get {
                return ResourceManager.GetString("UpdateLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [yellow]Update sources.json[/].
        /// </summary>
        internal static string UpdateSourcesJson {
            get {
                return ResourceManager.GetString("UpdateSourcesJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [palegreen1]Yes[/].
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
