name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-osx:
    runs-on: macos-latest
    env: 
      TEAM_ID: XV53H7ABC6
      SIGNING_IDENTITY: 1
      
    steps:
      - name: Setup Keychain
        run: |
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD}}" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD}}" build.keychain
          echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "${{ secrets.MACOS_CERTIFICATE_PWD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          xcrun notarytool store-credentials "AC_PASSWORD" --apple-id "${{ secrets.APPLE_ID }}" --team-id ${{ secrets.TEAM_ID }} --password "${{ secrets.NOTARY_TOOL_PASSWORD }}"
          
      - name: Publish
        run: dotnet publish -c Release -r osx-x64 -o $RUNNER_TEMP/MyApp.app/Contents/MacOS MyApp.csproj
        
      - name: Codesign app
        run: |
            find "$RUNNER_TEMP/MyApp.app/Contents/MacOS/"|while read fname; do
              if [ -f "$fname" ]
              then
                  echo "[INFO] Signing $fname"
                  codesign --force --timestamp --options=runtime --entitlements MyApp.entitlements --sign "${{ env.$SIGNING_IDENTITY }}" "$fname"
              fi
            done
            codesign --force --timestamp --options=runtime --entitlements MyApp.entitlements --sign "${{ env.SIGNING_IDENTITY }}" "$RUNNER_TEMP/MyApp.app"    
          
      - name: Notarise app
        run: |
            ditto -c -k --sequesterRsrc --keepParent "$RUNNER_TEMP/MyApp.app" "$RUNNER_TEMP/MyApp.zip"
            xcrun notarytool submit "$RUNNER_TEMP/MyApp.zip" --wait --keychain-profile "AC_PASSWORD"
            xcrun stapler staple "$RUNNER_TEMP/MyApp.app"